name: Checker-Trigger

on:
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  test:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hello**
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
